-- Rollback acceptance only. NOT a migration; no real photos are uploaded.
begin;
create temporary table photo_test_results(result text);
do $$
declare cid uuid:='9acb54bc-6d61-45af-b7ca-86249d87de28'; aid uuid:=gen_random_uuid(); bid uuid:=gen_random_uuid(); payload jsonb;
  rid uuid; linked uuid:=gen_random_uuid(); other uuid:=gen_random_uuid(); denied boolean; n integer;
begin
  perform set_config('request.jwt.claim.sub','e667b8d9-b74d-47e7-b9b6-b91823b01128',true);
  update public.community_release_checks set status='passed' where community_id=cid;
  update public.communities set status='published' where id=cid;
  insert into public.community_cohorts(community_id,eligibility_scope,status,welcome_message,introduction_prompt,created_by,follow_up_until)
    values(cid,'active_members','active','A transaction-only photo test.','Share a question in this rollback-only fixture.','86829233-6deb-4335-8370-468d61dce51e',now()+interval '1 day')
    on conflict(community_id) do update set status='active',follow_up_until=now()+interval '1 day';
  perform set_config('request.jwt.claim.sub','86829233-6deb-4335-8370-468d61dce51e',true);
  if public.create_community_photo_album(cid,aid,'Our memories','A transaction-only photo album.')<>aid then raise exception 'Host album creation failed'; end if;
  if public.create_community_photo_album(cid,aid,'Our memories','A transaction-only photo album.')<>aid then raise exception 'Retry changed album'; end if;
  if (select count(*) from public.community_photo_albums where id=aid)<>1 then raise exception 'Retry duplicated album'; end if;
  denied:=false;
  begin perform public.reserve_community_album_photos(aid,bid,1,true);
  exception when others then if sqlerrm='Photo uploads are not open yet' then denied:=true; else raise; end if; end;
  if not denied then raise exception 'Unfinished upload feature opened'; end if;
  update public.community_photo_settings set uploads_enabled=true where community_id=cid;
  payload:=public.reserve_community_album_photos(aid,bid,10,true);
  if jsonb_array_length(payload)<>10 or payload<>public.reserve_community_album_photos(aid,bid,10,true) then raise exception 'Reservation retry duplicated photos'; end if;
  if (select sum(reserved_bytes) from public.community_album_photos where batch_id=bid)<>11141120 then raise exception 'Incorrect reserved allowance'; end if;
  denied:=false;
  begin perform public.reserve_community_album_photos(aid,gen_random_uuid(),11,true);
  exception when others then if sqlerrm='Choose between 1 and 10 photos' then denied:=true; else raise; end if; end;
  if not denied then raise exception 'Batch limit bypass'; end if;
  denied:=false;
  begin perform public.reserve_community_album_photos(aid,gen_random_uuid(),1,false);
  exception when others then if sqlerrm='Confirm you have permission from the people pictured' then denied:=true; else raise; end if; end;
  if not denied then raise exception 'Consent bypass'; end if;
  perform set_config('request.jwt.claim.sub','9b4cde5d-578e-442f-b9ee-2e304e88ae46',true);
  denied:=false;
  begin perform public.reserve_community_album_photos(aid,gen_random_uuid(),1,true);
  exception when others then if sqlerrm='This album is not accepting your photos' then denied:=true; else raise; end if; end;
  if not denied then raise exception 'Hosts-only bypass'; end if;
  denied:=false;
  begin perform public.save_community_photo_album_settings(aid,'members',false);
  exception when others then if sqlerrm='Active Community Host access required' then denied:=true; else raise; end if; end;
  if not denied then raise exception 'Member changed Host setting'; end if;
  perform set_config('request.jwt.claim.sub','86829233-6deb-4335-8370-468d61dce51e',true);
  perform public.save_community_photo_album_settings(aid,'review',false);
  perform set_config('request.jwt.claim.sub','9b4cde5d-578e-442f-b9ee-2e304e88ae46',true);
  perform public.reserve_community_album_photos(aid,gen_random_uuid(),10,true);
  perform public.reserve_community_album_photos(aid,gen_random_uuid(),10,true);
  denied:=false;
  begin perform public.reserve_community_album_photos(aid,gen_random_uuid(),1,true);
  exception when others then if sqlerrm='You can add up to 20 photos a day in this Community' then denied:=true; else raise; end if; end;
  if not denied then raise exception 'Daily limit bypass'; end if;
  perform set_config('request.jwt.claim.sub','86829233-6deb-4335-8370-468d61dce51e',true);
  perform public.save_community_photo_album_settings(aid,'members',true);
  denied:=false;
  begin perform public.reserve_community_album_photos(aid,gen_random_uuid(),1,true);
  exception when others then if sqlerrm='This album is not accepting your photos' then denied:=true; else raise; end if; end;
  if not denied then raise exception 'Closed album bypass'; end if;
  perform public.save_community_photo_album_settings(aid,'members',false);
  update public.community_album_photos set reservation_expires_at=now()-interval '1 hour' where album_id=aid;
  update public.community_photo_settings set allowance_bytes=30*1114112 where community_id=cid;
  denied:=false;
  begin perform public.reserve_community_album_photos(aid,gen_random_uuid(),1,true);
  exception when others then if sqlerrm='Your Community photo allowance is full' then denied:=true; else raise; end if; end;
  if not denied then raise exception 'Expired reservation freed bytes without cleanup'; end if;
  update public.community_photo_settings set allowance_bytes=524288000 where community_id=cid;
  for n in 1..7 loop perform public.reserve_community_album_photos(aid,gen_random_uuid(),10,true); end loop;
  denied:=false;
  begin perform public.reserve_community_album_photos(aid,gen_random_uuid(),1,true);
  exception when others then if sqlerrm='This album has reached its 100 photo limit' then denied:=true; else raise; end if; end;
  if not denied then raise exception 'Album limit bypass'; end if;
  rid:=(public.create_community_video_discussion(cid,gen_random_uuid(),'Photo test video','A transaction-only video for album linking.','M7lc1UVf-VE',true)->>'room_id')::uuid;
  perform public.create_community_photo_album(cid,linked,'Gathering photos','Photos tied to the existing discussion.',rid);
  perform public.create_community_photo_album(cid,other,'More gathering photos','A second album sharing the same discussion.',rid);
  if (select post_id from public.community_photo_albums where id=linked)<>(select post_id from public.community_photo_albums where id=other) then raise exception 'Duplicate gathering conversation'; end if;
  update public.community_cohorts set status='read_only' where community_id=cid;
  if public.can_access_community_photos(cid,true) then raise exception 'Read-only Community accepted changes'; end if;
  update public.community_cohorts set status='active' where community_id=cid;
  perform set_config('request.jwt.claim.sub','9b4cde5d-578e-442f-b9ee-2e304e88ae46',true);
  update public.community_memberships set status='removed' where community_id=cid and user_id=auth.uid();
  if public.can_access_community_photos(cid) then raise exception 'Removed member access'; end if;
  perform set_config('request.jwt.claim.sub','8beb9661-20b6-407e-b5e8-66d2bfb266b3',true);
  if public.can_access_community_photos(cid) then raise exception 'Outsider access'; end if;
  if has_table_privilege('authenticated','public.community_album_photos','select') or has_table_privilege('anon','public.community_photo_albums','select')
    or has_function_privilege('anon','public.reserve_community_album_photos(uuid,uuid,integer,boolean)','execute') then raise exception 'Direct/anonymous access'; end if;
  insert into photo_test_results values('PASS: Host create/retry; uploads closed by default; batch retry/size/consent; Host-only and closed album; settings denial; member daily limit; expired bytes retained; 100-album limit; shared gathering thread; read-only/removed/outsider/direct/anonymous denial');
end;
$$;
select * from photo_test_results;
rollback;
