-- Transaction-only acceptance. NOT a migration; no real binaries are uploaded.
begin;
create temporary table photo_safety_results(result text);
do $$
declare cid uuid:='9acb54bc-6d61-45af-b7ca-86249d87de28'; aid uuid:=gen_random_uuid();
 member_id uuid:='9b4cde5d-578e-442f-b9ee-2e304e88ae46'; host_id uuid:='86829233-6deb-4335-8370-468d61dce51e';
 admin_id uuid:='e667b8d9-b74d-47e7-b9b6-b91823b01128'; photo uuid; pending_photo uuid; upload jsonb; report uuid; pending_report uuid; reply uuid; denied boolean; result jsonb;
begin
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 update public.community_release_checks set status='passed' where community_id=cid;
 update public.communities set status='published' where id=cid;
 insert into public.community_cohorts(community_id,eligibility_scope,status,welcome_message,introduction_prompt,created_by,follow_up_until)
 values(cid,'active_members','active','Transaction-only photo test.','Share a question in this rollback-only fixture.',host_id,now()+interval '1 day')
 on conflict(community_id) do update set status='active',follow_up_until=now()+interval '1 day';
 perform set_config('request.jwt.claim.sub',host_id::text,true);
 perform public.create_community_photo_album(cid,aid,'Photo safety test','Transaction-only album.');
 perform public.save_community_photo_album_settings(aid,'members',false);
 update public.community_photo_settings set uploads_enabled=true where community_id=cid;
 perform set_config('request.jwt.claim.sub',member_id::text,true);
 photo:=(public.reserve_community_album_photos(aid,gen_random_uuid(),1,true)->0->>'id')::uuid;
 execute 'set local role service_role';
 upload:=public.claim_community_photo_upload(photo,member_id);
 perform public.finish_community_photo_upload(photo,member_id,(upload->>'token')::uuid,1000,120,80,'Original captured caption');
 execute 'reset role';
 reply:=public.reply_to_community_album(aid,'A lasting album reply from a member.');
 result:=public.get_community_album_discussion(aid);
 if jsonb_array_length(result->'comments')<>1 or result->>'post_id'<>(select post_id::text from public.community_photo_albums where id=aid) then raise exception 'Album conversation continuity failed'; end if;
 update public.community_cohorts set status='read_only' where community_id=cid;
 if not (public.get_community_album_discussion(aid)->>'read_only')::boolean then raise exception 'Read-only state missing'; end if;
 denied:=false; begin perform public.reply_to_community_album(aid,'This must not save.'); exception when others then if sqlerrm='This Community is read only' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'Read-only reply accepted'; end if;
 update public.community_cohorts set status='active' where community_id=cid;
 perform set_config('request.jwt.claim.sub',host_id::text,true);
 report:=public.report_community_photo(photo,'privacy','This member photo needs a permission check.');
 if public.report_community_photo(photo,'other','Retry should return the original report.')<>report then raise exception 'Duplicate report created'; end if;
 if (select evidence_snapshot->>'caption' from public.community_photo_reports where id=report)<>'Original captured caption' then raise exception 'Evidence not captured'; end if;
 denied:=false; begin perform public.list_community_photo_reports(); exception when others then if sqlerrm='Moderator role required' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'Host read Admin reports'; end if;
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 if jsonb_array_length(public.list_community_photo_reports())<>1 then raise exception 'Admin queue missing report'; end if;
 if public.get_community_reported_photo_file(report,photo) is null then raise exception 'Reported binary scope missing'; end if;
 denied:=false; begin perform public.get_community_reported_photo_file(report,gen_random_uuid()); exception when others then if sqlerrm='Reported photo unavailable' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'Unrelated binary scope accepted'; end if;
 perform public.review_community_photo_report(report,'hide','Permission needs to be confirmed first.');
 perform set_config('request.jwt.claim.sub',host_id::text,true);
 denied:=false; begin perform public.review_community_album_photo(photo,'restore'); exception when others then if sqlerrm='The safety team must release this photo first' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'Host bypassed Admin safety hold'; end if;
 perform set_config('request.jwt.claim.sub',member_id::text,true);
 denied:=false; begin perform public.get_community_photo_file(photo); exception when others then if sqlerrm='This photo is unavailable' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'Member saw Admin-hidden photo'; end if;
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 perform public.review_community_photo_report(report,'restore','Permission was confirmed for this fixture.');
 perform set_config('request.jwt.claim.sub',member_id::text,true);
 if public.get_community_photo_file(photo) is null then raise exception 'Admin release did not restore photo'; end if;
 report:=public.report_community_photo(photo,'privacy','I need this photograph removed from the Community.');
 perform public.review_community_album_photo(photo,'remove');
 update public.community_album_photos set removed_at=now()-interval '8 days' where id=photo;
 execute 'set local role service_role'; result:=public.claim_community_photo_cleanup(); execute 'reset role';
 if jsonb_array_length(result)<>0 then raise exception 'Open-report evidence cleaned too soon'; end if;
 update public.community_photo_reports set created_at=now()-interval '31 days' where id=report;
 execute 'set local role service_role'; result:=public.claim_community_photo_cleanup(); execute 'reset role';
 if jsonb_array_length(result)<>1 then raise exception 'Report hold exceeded 30 days'; end if;
 perform set_config('request.jwt.claim.sub','8beb9661-20b6-407e-b5e8-66d2bfb266b3',true);
 denied:=false; begin perform public.get_community_album_discussion(aid); exception when others then if sqlerrm='Active Community membership required' then denied:=true; else raise; end if; end;
 if not denied then raise exception 'Outsider read album conversation'; end if;
 perform set_config('request.jwt.claim.sub',host_id::text,true);
 perform public.save_community_photo_album_settings(aid,'review',false);
 perform set_config('request.jwt.claim.sub',member_id::text,true);
 pending_photo:=(public.reserve_community_album_photos(aid,gen_random_uuid(),1,true)->0->>'id')::uuid;
 execute 'set local role service_role'; upload:=public.claim_community_photo_upload(pending_photo,member_id);
 perform public.finish_community_photo_upload(pending_photo,member_id,(upload->>'token')::uuid,1000,120,80,'Pending photo'); execute 'reset role';
 pending_report:=public.report_community_photo(pending_photo,'privacy','Check permission for this pending photograph.');
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 perform public.review_community_photo_report(pending_report,'hide','Hold the photograph for a permission check.');
 perform public.review_community_photo_report(pending_report,'restore','Permission confirmed, but Host review is still required.');
 if (select status from public.community_album_photos where id=pending_photo)<>'pending' then raise exception 'Safety release bypassed Host approval'; end if;
 if has_table_privilege('authenticated','public.community_photo_reports','select') or has_function_privilege('anon','public.report_community_photo(uuid,text,text)','execute') then raise exception 'Direct or anonymous report access'; end if;
 insert into photo_safety_results values('PASS: scoped reports, retry, evidence, Admin hold/release, pending approval preservation, member/Host denial, bounded cleanup and lasting album replies');
end;
$$;
select * from photo_safety_results;
rollback;
