"use client";
import { FormEvent, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export type MembershipPlan={plan_id:string;slug:string;name:string;description:string;price_minor:number;currency:string;duration_months:number;grace_days:number;payment_mode:string;status:string;current_period_id:string|null;current_status:string|null;current_starts_at:string|null;current_ends_at:string|null;grace_ends_at:string|null};

export function MembershipCenter({plans}:{plans:MembershipPlan[]}){
 const supabase=useMemo(()=>createClient(),[]);const[busy,setBusy]=useState("");const[message,setMessage]=useState("");
 const current=plans.find(plan=>plan.current_period_id)?.current_status;
 async function purchase(event:FormEvent<HTMLFormElement>,plan:MembershipPlan){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(plan.plan_id);setMessage("");
  if(plan.payment_mode==="automatic"){const response=await fetch("/api/payments/paystack/initialize",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({membershipPlanId:plan.plan_id})});const body=await response.json()as{authorizationUrl?:string;error?:string};setBusy("");if(body.authorizationUrl){window.location.assign(body.authorizationUrl);return}setMessage(body.error??"Checkout could not start.");return}
  const{error}=await supabase.rpc("create_membership_order",{p_plan_id:plan.plan_id,p_manual_reference:form.get("reference"),p_manual_note:form.get("note")});setBusy("");setMessage(error?error.message:"Your payment details are awaiting private admin review.");if(!error)window.location.reload();
 }
 return <><section className="membership-status"><div><p className="eyebrow">Membership standing</p><h2>{current?current.replace("_"," "):"Choose your membership"}</h2><p>Membership periods are recorded individually, renewals are added after your current term, and grace status remains visible to you.</p></div>{plans.find(plan=>plan.current_period_id)?.current_ends_at?<dl><dt>Current term ends</dt><dd>{new Intl.DateTimeFormat("en-KE",{dateStyle:"long"}).format(new Date(plans.find(plan=>plan.current_period_id)!.current_ends_at!))}</dd></dl>:null}</section><section className="membership-grid">{plans.map(plan=><article key={plan.plan_id}><span>{plan.duration_months} month term</span><h2>{plan.name}</h2><p>{plan.description}</p><strong>{plan.currency} {(plan.price_minor/100).toLocaleString("en-KE",{minimumFractionDigits:2})}</strong><small>{plan.grace_days} day renewal grace · {plan.payment_mode.replace("_"," ")}</small>{plan.payment_mode==="closed"?<button disabled>Enrollment closed</button>:<form onSubmit={event=>void purchase(event,plan)}>{plan.payment_mode==="manual_review"?<><label>Payment reference<input name="reference"required minLength={3}/></label><label>Private payment note<textarea name="note"required minLength={5}/></label></>:null}<button className="button button-primary"disabled={busy===plan.plan_id}>{busy===plan.plan_id?"Processing…":plan.current_period_id?"Renew membership":"Activate membership"}</button></form>}</article>)}</section>{message?<p className="network-message"role="status">{message}</p>:null}</>;
}
