"use client";
import { FormEvent, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Ticket={currency:string;description:string|null;id:string;inventory_quantity:number|null;name:string;price_minor:number};
export function EventRegistrationForm({eventId,eventTitle,mode,tickets,existingStatus}:{eventId:string;eventTitle:string;mode:string;tickets:Ticket[];existingStatus:string|null}){
 const supabase=useMemo(()=>createClient(),[]);const [ticketId,setTicketId]=useState(tickets[0]?.id??"");const [quantity,setQuantity]=useState(1);const [note,setNote]=useState("");const [reference,setReference]=useState("");const [paymentNote,setPaymentNote]=useState("");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 const ticket=tickets.find(x=>x.id===ticketId); async function submit(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");if(mode==="automatic"){try{const response=await fetch("/api/payments/paystack/initialize",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({attendeeNote:note,eventId,quantity,ticketTypeId:ticketId})});const payload=await response.json() as {authorizationUrl?:string;error?:string};if(!response.ok||!payload.authorizationUrl)throw new Error(payload.error||"Checkout initialization failed");window.location.assign(payload.authorizationUrl);return}catch(error){setBusy(false);setMessage(error instanceof Error?error.message:"Secure checkout could not be initialized.");return}}const {error}=await supabase.rpc("create_event_registration",{p_attendee_note:note,p_event_id:eventId,p_manual_note:paymentNote,p_manual_reference:reference,p_quantity:quantity,p_ticket_type_id:ticketId||null});setBusy(false);setMessage(error?error.message:mode==="waitlist"?"You are on the waitlist. We will contact you when a seat opens.":"Your registration is awaiting manual review. No automatic charge has been made.");if(!error)setTimeout(()=>window.location.reload(),1200)}
 if(existingStatus)return <div className="registration-status-card"><p className="eyebrow">Registration received</p><h2>{existingStatus.replace("_"," ")}</h2><p>Your request is recorded. Status changes are issued only after payment verification or an audited administrator review.</p></div>;
 return <form className="event-registration-form" onSubmit={submit}><header><p className="eyebrow">Request your seat</p><h1>{eventTitle}</h1><p>{mode==="manual_review"?"Submit your ticket request and any offline payment reference. An administrator will verify it before access is granted.":mode==="waitlist"?"Join the waitlist and we will contact you when a seat becomes available.":"Choose your ticket and continue to Paystack's secure checkout. Access is granted only after server verification."}</p></header>{mode!=="waitlist"?<div className="ticket-choice-list">{tickets.map(item=><label className={ticketId===item.id?"selected":""} key={item.id}><input type="radio" name="ticket" value={item.id} checked={ticketId===item.id} onChange={()=>setTicketId(item.id)}/><span><strong>{item.name}</strong><small>{item.description}</small></span><b>{item.currency} {(item.price_minor/100).toLocaleString("en-KE",{minimumFractionDigits:2})}</b></label>)}</div>:null}<div className="form-grid registration-fields">{mode!=="waitlist"?<label>Quantity<input type="number" min="1" max="10" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label>:null}<label className="form-wide">Note for the event team<textarea rows={3} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></label>{mode==="manual_review"?<><label>Payment/reference number<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Optional until payment is made"/></label><label>Payment note<input value={paymentNote} onChange={e=>setPaymentNote(e.target.value)} placeholder="Method, date, or context"/></label></>:null}</div>{ticket&&mode!=="waitlist"?<div className="registration-total"><span>Total</span><strong>{ticket.currency} {((ticket.price_minor*quantity)/100).toLocaleString("en-KE",{minimumFractionDigits:2})}</strong></div>:null}<button className="button button-primary" disabled={busy||mode==="closed"||((mode!=="waitlist")&&!ticketId)}>{busy?"Submitting…":mode==="waitlist"?"Join waitlist":mode==="automatic"?"Continue to secure payment":"Submit for manual review"}</button>{message?<p className="manager-message" role="status">{message}</p>:null}</form>
}
