"use client";
import { FormEvent, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import type { AdminEvent } from "@/components/admin/event-manager";

export type AdminTicket={currency:string;description:string|null;event_id:string;id:string;inventory_quantity:number|null;name:string;price_minor:number;sales_end_at:string|null;sales_start_at:string|null;sort_order:number;status:"draft"|"on_sale"|"paused"|"sold_out"|"archived"};
export type AdminRegistration={created_at:string;currency:string;display_name:string|null;email:string;event_id:string;order_id:string;order_reference:string;processing_mode:string;quantity:number;status:string;submitted_reference:string|null;submitter_note:string|null;ticket_name:string;total_minor:number;user_id:string};
const blank={id:null as string|null,name:"Founding table",description:"",price:"",currency:"KES",inventory:"",salesStart:"",salesEnd:"",status:"draft" as AdminTicket["status"],sortOrder:"0"};
const local=(value:string|null)=>value?new Date(new Date(value).getTime()-new Date(value).getTimezoneOffset()*60000).toISOString().slice(0,16):"";

export function RegistrationManager({events,initialTickets,initialRegistrations,migrationReady}:{events:AdminEvent[];initialTickets:AdminTicket[];initialRegistrations:AdminRegistration[];migrationReady:boolean}){
 const supabase=useMemo(()=>createClient(),[]); const [eventId,setEventId]=useState(events[0]?.id??""); const [form,setForm]=useState(blank); const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
 const tickets=initialTickets.filter(x=>x.event_id===eventId); const registrations=initialRegistrations.filter(x=>x.event_id===eventId);
 function fail(error:{message:string}|null){if(!error)return false;setBusy(false);setMessage(error.message.includes("schema cache")||error.message.includes("Could not find")?"Apply 20260722130000_registration_commerce_foundation.sql in Supabase, then retry.":error.message);return true}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");const {error}=await supabase.rpc("save_ticket_type",{p_currency:form.currency,p_description:form.description,p_event_id:eventId,p_inventory:form.inventory?Number(form.inventory):null,p_name:form.name,p_price_minor:Math.round(Number(form.price)*100),p_sales_end:form.salesEnd?new Date(form.salesEnd).toISOString():null,p_sales_start:form.salesStart?new Date(form.salesStart).toISOString():null,p_sort_order:Number(form.sortOrder)||0,p_status:form.status,p_ticket_id:form.id});if(fail(error))return;setBusy(false);setMessage("Ticket saved in minor units and audit logged.");window.location.reload()}
 async function review(orderId:string,action:"approve"|"reject"){const note=window.prompt(action==="approve"?"Approval note (optional)":"Reason for rejection")??"";if(action==="reject"&&!note.trim())return;setBusy(true);const {error}=await supabase.rpc("review_manual_registration",{p_action:action,p_order_id:orderId,p_reviewer_note:note});if(fail(error))return;setBusy(false);setMessage(`Registration ${action}d and audit logged.`);window.location.reload()}
 if(!migrationReady)return <section className="admin-section" id="registrations"><div className="admin-empty"><strong>Registration database update required</strong><p>Apply <code>20260722130000_registration_commerce_foundation.sql</code>.</p></div></section>; if(!events.length)return null;
 return <section className="admin-section registration-manager" id="registrations"><div className="admin-section-heading"><div><p className="eyebrow">Registration operations</p><h2>Tickets and manual review</h2><p>Prices are stored in minor units. Manual approval and verified online payment will grant the same idempotent entitlement.</p></div><label className="event-content-select">Working event<select value={eventId} onChange={e=>{setEventId(e.target.value);setForm(blank)}}>{events.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label></div>
 <div className="registration-admin-grid"><aside className="content-record-list"><div><strong>{tickets.length} ticket types</strong><button type="button" onClick={()=>setForm(blank)}>New ticket</button></div>{tickets.map(t=><button key={t.id} type="button" className={form.id===t.id?"selected":""} onClick={()=>setForm({id:t.id,name:t.name,description:t.description??"",price:(t.price_minor/100).toFixed(2),currency:t.currency,inventory:t.inventory_quantity?.toString()??"",salesStart:local(t.sales_start_at),salesEnd:local(t.sales_end_at),status:t.status,sortOrder:String(t.sort_order)})}><span>{t.name}</span><small>{t.currency} {(t.price_minor/100).toLocaleString("en-KE",{minimumFractionDigits:2})} · {t.status}</small></button>)}</aside><form className="content-editor" onSubmit={save}><div className="form-grid"><label>Ticket name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Price<input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required/></label><label>Currency<input maxLength={3} value={form.currency} onChange={e=>setForm({...form,currency:e.target.value.toUpperCase()})} required/></label><label>Inventory<input type="number" min="1" value={form.inventory} onChange={e=>setForm({...form,inventory:e.target.value})} placeholder="Unlimited if blank"/></label><label>Sales open<input type="datetime-local" value={form.salesStart} onChange={e=>setForm({...form,salesStart:e.target.value})}/></label><label>Sales close<input type="datetime-local" value={form.salesEnd} onChange={e=>setForm({...form,salesEnd:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as AdminTicket["status"]})}><option value="draft">Draft</option><option value="on_sale">On sale</option><option value="paused">Paused</option><option value="sold_out">Sold out</option><option value="archived">Archived</option></select></label><label className="form-wide">Description<textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><button className="button button-primary" disabled={busy}>{busy?"Saving…":"Save ticket"}</button></form></div>
 <div className="registration-review"><p className="eyebrow">Registration queue</p>{registrations.length?<div className="member-table-wrap"><table className="member-table"><thead><tr><th>Applicant</th><th>Order</th><th>Ticket</th><th>Amount</th><th>Status</th><th></th></tr></thead><tbody>{registrations.map(r=><tr key={r.order_id}><td><strong>{r.display_name||r.email}</strong><small>{r.email}</small></td><td>{r.order_reference}<small>{r.submitted_reference||"No manual reference"}</small></td><td>{r.ticket_name} × {r.quantity}</td><td>{r.currency} {(r.total_minor/100).toLocaleString("en-KE",{minimumFractionDigits:2})}</td><td><span className="member-status">{r.status.replace("_"," ")}</span></td><td>{r.status==="pending_review"?<div className="member-actions"><button disabled={busy} onClick={()=>void review(r.order_id,"approve")}>Approve</button><button className="danger-action" disabled={busy} onClick={()=>void review(r.order_id,"reject")}>Reject</button></div>:null}</td></tr>)}</tbody></table></div>:<div className="admin-empty"><strong>No registrations yet</strong><p>Member requests will appear here with payment mode and review evidence.</p></div>}</div>{message?<p className="manager-message content-manager-message">{message}</p>:null}</section>
}
