"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import type { SupportMessage } from "@/components/member/support-center";

export type AdminSupportTicket={ticket_id:string;reference:string;requester_id:string;email:string;display_name:string|null;category:string;subject:string;description:string;status:string;priority:string;assigned_email:string|null;response_due_at:string;created_at:string;updated_at:string};
const label=(value:string)=>value.replaceAll("_"," ");
const date=(value:string)=>new Intl.DateTimeFormat("en-KE",{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit"}).format(new Date(value));

export function SupportInbox({adminEmail,tickets,messages,selectedTicketId}:{adminEmail:string;tickets:AdminSupportTicket[];messages:SupportMessage[];selectedTicketId:string|null}) {const supabase=useMemo(()=>createClient(),[]);const router=useRouter();const selected=tickets.find(item=>item.ticket_id===selectedTicketId)??null;const [reply,setReply]=useState("");const [status,setStatus]=useState(selected?.status??"open");const [priority,setPriority]=useState(selected?.priority??"normal");const [assignee,setAssignee]=useState(selected?.assigned_email??adminEmail);const [note,setNote]=useState("");const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{setStatus(selected?.status??"open");setPriority(selected?.priority??"normal");setAssignee(selected?.assigned_email??adminEmail)},[adminEmail,selected]);
  useEffect(()=>{if(!selectedTicketId)return;const channel=supabase.channel(`admin-support:${selectedTicketId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"support_messages",filter:`ticket_id=eq.${selectedTicketId}`},()=>router.refresh()).subscribe();return()=>{void supabase.removeChannel(channel)}},[router,selectedTicketId,supabase]);
  async function send(event:FormEvent){event.preventDefault();if(!selectedTicketId)return;setBusy(true);const {error}=await supabase.rpc("reply_support_ticket",{p_body:reply,p_ticket_id:selectedTicketId});setBusy(false);setNotice(error?error.message:"Reply sent.");if(!error){setReply("");router.refresh()}}
  async function manage(event:FormEvent){event.preventDefault();if(!selectedTicketId)return;setBusy(true);const {error}=await supabase.rpc("manage_support_ticket",{p_assignee_email:assignee,p_note:note,p_priority:priority,p_status:status,p_ticket_id:selectedTicketId});setBusy(false);setNotice(error?error.message:"Request updated.");if(!error){setNote("");router.refresh()}}
  return <div className="support-shell admin-support-shell"><aside className="support-sidebar"><header><p className="eyebrow">Operations</p><h1>Support inbox</h1><p>{tickets.filter(item=>!["resolved","closed"].includes(item.status)).length} requests need operational visibility.</p></header><div className="support-ticket-list">{tickets.map(ticket=><Link className={ticket.ticket_id===selectedTicketId?"selected":""} href={`/admin/support?ticket=${ticket.ticket_id}`} key={ticket.ticket_id}><span><strong>{ticket.subject}</strong><small>{ticket.display_name||ticket.email} · {ticket.reference}</small></span><b className={`support-state ${ticket.status}`}>{label(ticket.status)}</b></Link>)}</div></aside><section className="support-panel">{selected?<><header><div><p className="eyebrow">{selected.reference} · {label(selected.category)} · {selected.email}</p><h2>{selected.subject}</h2></div><span className={`support-state ${selected.status}`}>{label(selected.status)}</span></header><div className="support-thread"><article className="support-opening"><div><strong>{selected.display_name||selected.email}</strong><p>{selected.description}</p><time>{date(selected.created_at)}</time></div></article>{messages.map(message=><article className={message.is_staff?"staff":"own"} key={message.id}><div><strong>{message.is_staff?"Support team":selected.display_name||selected.email}</strong><p>{message.body}</p><time>{date(message.created_at)}</time></div></article>)}</div><form className="support-composer" onSubmit={send}><label><span className="sr-only">Reply</span><textarea rows={3} maxLength={4000} required value={reply} onChange={event=>setReply(event.target.value)} placeholder="Reply as Her Africa Table support…"/></label><button className="button button-primary" disabled={busy||!reply.trim()}>Send reply</button></form><form className="support-admin-controls" onSubmit={manage}><label>Status<select value={status} onChange={event=>setStatus(event.target.value)}>{["open","in_progress","waiting_member","resolved","closed"].map(item=><option key={item}>{item}</option>)}</select></label><label>Priority<select value={priority} onChange={event=>setPriority(event.target.value)}>{["low","normal","high","urgent"].map(item=><option key={item}>{item}</option>)}</select></label><label>Assignee email<input type="email" value={assignee} onChange={event=>setAssignee(event.target.value)}/></label><label className="support-note">Internal action note (shared with member)<input maxLength={4000} value={note} onChange={event=>setNote(event.target.value)}/></label><button className="button button-outline" disabled={busy}>Save operations</button></form></>:<div className="conversation-placeholder"><p className="eyebrow">Member care</p><h2>Select a request.</h2><p>Urgent and high-priority requests are ordered first.</p></div>}{notice?<p className="message-status" role="status">{notice}</p>:null}</section></div>}
