begin;
create table public.product_events(id bigint generated always as identity primary key,event_name text not null check(event_name in('member_activated','order_fulfilled','connection_accepted','message_sent','marketplace_post_created','community_post_created','course_enrolled','circle_response_created','perk_reserved','support_requested')),actor_id uuid references auth.users(id)on delete set null,subject_type text not null check(char_length(subject_type)between 2 and 60),metadata jsonb not null default'{}'::jsonb check(jsonb_typeof(metadata)='object'and octet_length(metadata::text)<=2048),is_test_event boolean not null default false,occurred_at timestamptz not null default now());
create index product_events_time_idx on public.product_events(occurred_at desc);create index product_events_name_time_idx on public.product_events(event_name,occurred_at desc);create index product_events_actor_time_idx on public.product_events(actor_id,occurred_at desc)where actor_id is not null and not is_test_event;
create table public.launch_readiness_targets(metric_key text primary key check(metric_key~'^[a-z0-9_]+$'),label text not null,description text not null,direction text not null check(direction in('minimum','maximum')),target_value bigint not null check(target_value>=0),sort_order integer not null default 0,updated_by uuid references auth.users(id)on delete set null,updated_at timestamptz not null default now());
insert into public.launch_readiness_targets(metric_key,label,description,direction,target_value,sort_order)values
('real_active_members','Active members','Real, non-test accounts with active access.','minimum',10,10),
('completed_onboarding','Completed onboarding','Real active members with complete onboarding.','minimum',10,20),
('published_events','Published events','Events visible through the production publishing boundary.','minimum',1,30),
('available_tickets','Available ticket types','Published ticket inventory configured for a live event.','minimum',1,40),
('fulfilled_orders','Fulfilled orders','Verified or manually approved orders completed end to end.','minimum',1,50),
('accepted_connections','Accepted connections','Permission-based relationships completed between real members.','minimum',3,60),
('monthly_active_members','30-day active members','Distinct real members producing a privacy-safe product event.','minimum',5,70),
('failed_notifications','Failed notifications','Delivery jobs requiring intervention.','maximum',0,80),
('payment_event_errors','Payment reconciliation errors','Provider events with unresolved processing errors.','maximum',0,90),
('open_safety_reports','Open safety reports','Member, marketplace or community reports awaiting an outcome.','maximum',0,100)
on conflict(metric_key)do nothing;
alter table public.product_events enable row level security;alter table public.launch_readiness_targets enable row level security;
create policy "Super admins read product analytics"on public.product_events for select to authenticated using(public.is_admin(array['super_admin']::public.app_role[]));
create policy "Super admins manage readiness targets"on public.launch_readiness_targets for all to authenticated using(public.is_admin(array['super_admin']::public.app_role[]))with check(public.is_admin(array['super_admin']::public.app_role[]));
create or replace function public.record_product_event(p_event_name text,p_actor_id uuid,p_subject_type text,p_metadata jsonb default'{}')returns void language plpgsql security definer set search_path=''as $$declare test_event boolean:=false;begin if p_event_name not in('member_activated','order_fulfilled','connection_accepted','message_sent','marketplace_post_created','community_post_created','course_enrolled','circle_response_created','perk_reserved','support_requested')then raise exception'Unsupported product event';end if;if p_actor_id is not null then select coalesce(is_test_account,false)into test_event from public.profiles where id=p_actor_id;end if;insert into public.product_events(event_name,actor_id,subject_type,metadata,is_test_event)values(p_event_name,p_actor_id,left(trim(p_subject_type),60),coalesce(p_metadata,'{}'),coalesce(test_event,false));end;$$;
create or replace function public.capture_product_insert()returns trigger language plpgsql security definer set search_path=''as $$declare actor uuid;begin actor:=nullif(to_jsonb(new)->>tg_argv[1],'')::uuid;perform public.record_product_event(tg_argv[0],actor,tg_table_name,jsonb_build_object('source',tg_table_name));return new;end;$$;
create or replace function public.capture_profile_activation()returns trigger language plpgsql security definer set search_path=''as $$begin if old.is_test_account is distinct from new.is_test_account then update public.product_events set is_test_event=new.is_test_account where actor_id=new.id;end if;if old.access_status is distinct from new.access_status and new.access_status='deleted'then update public.product_events set actor_id=null where actor_id=new.id;elsif old.access_status is distinct from new.access_status and new.access_status='active'then perform public.record_product_event('member_activated',new.id,'profile','{}');end if;return new;end;$$;
create or replace function public.capture_order_fulfillment()returns trigger language plpgsql security definer set search_path=''as $$begin if old.status is distinct from new.status and new.status='fulfilled'then perform public.record_product_event('order_fulfilled',new.user_id,'order',jsonb_build_object('order_type',new.order_type));end if;return new;end;$$;
create or replace function public.capture_connection_acceptance()returns trigger language plpgsql security definer set search_path=''as $$begin if old.status is distinct from new.status and new.status='accepted'then perform public.record_product_event('connection_accepted',new.requester_id,'connection','{}');end if;return new;end;$$;
create trigger analytics_profile_activation after update of access_status,is_test_account on public.profiles for each row execute function public.capture_profile_activation();
create trigger analytics_order_fulfillment after update of status on public.orders for each row execute function public.capture_order_fulfillment();
create trigger analytics_connection_acceptance after update of status on public.connections for each row execute function public.capture_connection_acceptance();
create trigger analytics_message_insert after insert on public.messages for each row execute function public.capture_product_insert('message_sent','sender_id');
create trigger analytics_marketplace_insert after insert on public.marketplace_posts for each row execute function public.capture_product_insert('marketplace_post_created','author_id');
create trigger analytics_community_post_insert after insert on public.community_posts for each row execute function public.capture_product_insert('community_post_created','author_id');
create trigger analytics_course_enrollment_insert after insert on public.course_enrollments for each row execute function public.capture_product_insert('course_enrolled','user_id');
create trigger analytics_circle_response_insert after insert on public.circle_prompt_responses for each row execute function public.capture_product_insert('circle_response_created','user_id');
create trigger analytics_perk_reservation_insert after insert on public.perk_redemptions for each row execute function public.capture_product_insert('perk_reserved','user_id');
create trigger analytics_support_insert after insert on public.support_tickets for each row execute function public.capture_product_insert('support_requested','requester_id');
create or replace function public.save_launch_readiness_target(p_metric_key text,p_target_value bigint)returns void language plpgsql security definer set search_path=''as $$begin if not public.is_admin(array['super_admin']::public.app_role[])then raise exception'Super admin required';end if;if p_target_value<0 then raise exception'Target must not be negative';end if;update public.launch_readiness_targets set target_value=p_target_value,updated_by=auth.uid(),updated_at=now()where metric_key=p_metric_key;if not found then raise exception'Unknown readiness metric';end if;insert into public.audit_events(actor_id,action,target_type,target_id,metadata)values(auth.uid(),'analytics.target_updated','launch_readiness_target',null,jsonb_build_object('metric_key',p_metric_key,'target_value',p_target_value));end;$$;
create or replace function public.get_product_analytics(p_days integer default 30)returns table(event_name text,real_events bigint,test_events bigint,unique_real_actors bigint,last_seen timestamptz)language plpgsql stable security definer set search_path=''as $$begin if not public.is_admin(array['super_admin']::public.app_role[])then raise exception'Super admin required';end if;return query select e.event_name,count(*)filter(where not e.is_test_event),count(*)filter(where e.is_test_event),count(distinct e.actor_id)filter(where not e.is_test_event),max(e.occurred_at)from public.product_events e where e.occurred_at>=now()-make_interval(days=>least(greatest(coalesce(p_days,30),1),365))group by e.event_name order by count(*)filter(where not e.is_test_event)desc,e.event_name;end;$$;
create or replace function public.get_launch_readiness_metrics()returns table(metric_key text,label text,description text,direction text,current_value bigint,target_value bigint,status text,sort_order integer)language plpgsql stable security definer set search_path=''as $$begin if not public.is_admin(array['super_admin']::public.app_role[])then raise exception'Super admin required';end if;return query with values_now as(
 select'real_active_members'::text key,count(*)::bigint value from public.profiles where access_status='active'and not is_test_account union all
 select'completed_onboarding',count(*)::bigint from public.profiles where access_status='active'and not is_test_account and onboarding_completed_at is not null and profile_completion=100 union all
 select'published_events',count(*)::bigint from public.events where status='published' union all
 select'available_tickets',count(*)::bigint from public.ticket_types t join public.events e on e.id=t.event_id where t.status='on_sale'and e.status='published'and(t.sales_start_at is null or t.sales_start_at<=now())and(t.sales_end_at is null or t.sales_end_at>now()) union all
 select'fulfilled_orders',count(*)::bigint from public.orders o join public.profiles p on p.id=o.user_id where o.status='fulfilled'and not p.is_test_account union all
 select'accepted_connections',count(*)::bigint from public.connections c join public.profiles a on a.id=c.user_low join public.profiles b on b.id=c.user_high where c.status='accepted'and not a.is_test_account and not b.is_test_account union all
 select'monthly_active_members',count(distinct actor_id)::bigint from public.product_events where occurred_at>=now()-interval'30 days'and not is_test_event union all
 select'failed_notifications',count(*)::bigint from public.notification_jobs where status='failed' union all
 select'payment_event_errors',count(*)::bigint from public.payment_events where error_message is not null union all
 select'open_safety_reports',(select count(*)from public.member_reports where status in('open','reviewing'))+(select count(*)from public.marketplace_reports where status in('open','reviewing'))+(select count(*)from public.community_post_reports where status in('open','reviewing'))
 )select t.metric_key,t.label,t.description,t.direction,coalesce(v.value,0),t.target_value,case when(t.direction='minimum'and coalesce(v.value,0)>=t.target_value)or(t.direction='maximum'and coalesce(v.value,0)<=t.target_value)then'ready'else'action_required'end,t.sort_order from public.launch_readiness_targets t left join values_now v on v.key=t.metric_key order by t.sort_order;end;$$;
revoke all on function public.record_product_event(text,uuid,text,jsonb)from public;revoke all on function public.save_launch_readiness_target(text,bigint)from public;grant execute on function public.save_launch_readiness_target(text,bigint)to authenticated;revoke all on function public.get_product_analytics(integer)from public;grant execute on function public.get_product_analytics(integer)to authenticated;revoke all on function public.get_launch_readiness_metrics()from public;grant execute on function public.get_launch_readiness_metrics()to authenticated;
comment on table public.product_events is'Privacy-minimized server events. Never store content, search terms, contact details, credentials, IP addresses or raw URLs.';
commit;
