begin;

insert into public.feature_flags(key,enabled,description)values('circles',false,'Deterministic member circles and guided prompts')on conflict(key)do nothing;
alter table public.notifications drop constraint if exists notifications_kind_check;alter table public.notifications add constraint notifications_kind_check check(kind in('system','network','community','event','registration','support','privacy'));
create or replace function public.enqueue_notification(p_user_id uuid,p_kind text,p_title text,p_body text,p_href text,p_dedupe_key text)returns uuid language plpgsql security definer set search_path=''as $$declare saved uuid;email_allowed boolean;in_app boolean;recipient text;begin if p_kind not in('system','network','community','event','registration','support','privacy')or nullif(trim(p_dedupe_key),'')is null then raise exception'Invalid notification';end if;if not exists(select 1 from public.profiles where id=p_user_id and access_status<>'deleted')then return null;end if;insert into public.notification_preferences(user_id)values(p_user_id)on conflict(user_id)do nothing;select np.in_app_enabled,case p_kind when'network'then np.email_network when'community'then np.email_network when'event'then np.email_events when'support'then np.email_support else true end,u.email::text into in_app,email_allowed,recipient from public.notification_preferences np join auth.users u on u.id=np.user_id where np.user_id=p_user_id;if in_app then insert into public.notifications(user_id,kind,title,body,href,dedupe_key)values(p_user_id,p_kind,left(trim(p_title),160),left(trim(p_body),1000),p_href,trim(p_dedupe_key))on conflict(user_id,dedupe_key)do update set title=excluded.title,body=excluded.body,href=excluded.href returning id into saved;end if;if email_allowed and recipient is not null then insert into public.notification_jobs(notification_id,user_id,template_key,to_email,payload,dedupe_key)values(saved,p_user_id,p_kind,recipient,jsonb_build_object('title',left(trim(p_title),160),'body',left(trim(p_body),1000),'href',p_href),trim(p_dedupe_key))on conflict(user_id,channel,dedupe_key)do nothing;end if;return saved;end;$$;

create table public.circle_cycles(
 id uuid primary key default gen_random_uuid(),slug text not null unique check(slug~'^[a-z0-9]+(?:-[a-z0-9]+)*$'),name text not null check(char_length(name)between 3 and 100),description text not null check(char_length(description)between 20 and 1500),starts_at timestamptz not null,ends_at timestamptz not null,group_size integer not null default 5 check(group_size between 3 and 8),include_test_accounts boolean not null default false,status text not null default'draft'check(status in('draft','open','matched','published','completed')),created_by uuid not null references auth.users(id)on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_at>starts_at)
);
create table public.circle_opt_ins(
 id uuid primary key default gen_random_uuid(),cycle_id uuid not null references public.circle_cycles(id)on delete cascade,user_id uuid not null references auth.users(id)on delete cascade,note text check(note is null or char_length(note)<=500),status text not null default'opted_in'check(status in('opted_in','withdrawn','placed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(cycle_id,user_id)
);
create table public.circles(
 id uuid primary key default gen_random_uuid(),cycle_id uuid not null references public.circle_cycles(id)on delete cascade,sequence integer not null check(sequence>0),name text not null,status text not null default'draft'check(status in('draft','published','completed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(cycle_id,sequence)
);
create table public.circle_memberships(
 id uuid primary key default gen_random_uuid(),circle_id uuid not null references public.circles(id)on delete cascade,cycle_id uuid not null references public.circle_cycles(id)on delete cascade,user_id uuid not null references auth.users(id)on delete restrict,role text not null default'member'check(role in('member','facilitator')),status text not null default'active'check(status in('active','left','removed')),match_score integer not null default 0 check(match_score between 0 and 100),match_explanation jsonb not null default'{}',joined_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(cycle_id,user_id),unique(circle_id,user_id)
);
create table public.circle_prompts(
 id uuid primary key default gen_random_uuid(),circle_id uuid not null references public.circles(id)on delete cascade,title text not null check(char_length(title)between 3 and 160),body text not null check(char_length(body)between 20 and 2000),opens_at timestamptz not null default now(),due_at timestamptz,status text not null default'published'check(status in('draft','published','archived')),created_by uuid not null references auth.users(id)on delete restrict,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(due_at is null or due_at>opens_at)
);
create table public.circle_prompt_responses(
 id uuid primary key default gen_random_uuid(),prompt_id uuid not null references public.circle_prompts(id)on delete cascade,user_id uuid not null references auth.users(id)on delete restrict,body text not null check(char_length(body)between 5 and 2000),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(prompt_id,user_id)
);
create index circle_opt_ins_cycle_idx on public.circle_opt_ins(cycle_id,status);create index circle_memberships_user_idx on public.circle_memberships(user_id,status);create index circle_prompts_circle_idx on public.circle_prompts(circle_id,status,opens_at desc);create index circle_responses_prompt_idx on public.circle_prompt_responses(prompt_id,created_at);

alter table public.circle_cycles enable row level security;alter table public.circle_opt_ins enable row level security;alter table public.circles enable row level security;alter table public.circle_memberships enable row level security;alter table public.circle_prompts enable row level security;alter table public.circle_prompt_responses enable row level security;
create or replace function public.circles_enabled()returns boolean language sql stable security definer set search_path=''as $$select coalesce((select enabled from public.feature_flags where key='circles'),false)$$;
create or replace function public.is_circle_member(p_circle_id uuid,p_user_id uuid)returns boolean language sql stable security definer set search_path=''as $$select exists(select 1 from public.circle_memberships where circle_id=p_circle_id and user_id=p_user_id and status='active')$$;
create policy "Members read available circle cycles"on public.circle_cycles for select to authenticated using((public.circles_enabled()and status in('open','matched','published','completed')and public.is_active_member(auth.uid()))or public.is_admin(array['super_admin']::public.app_role[]));
create policy "Members read own circle opt in"on public.circle_opt_ins for select to authenticated using((public.circles_enabled()and user_id=auth.uid())or public.is_admin(array['super_admin']::public.app_role[]));
create policy "Members read assigned circles"on public.circles for select to authenticated using((public.circles_enabled()and exists(select 1 from public.circle_memberships m where m.circle_id=id and m.user_id=auth.uid()and m.status='active'))or public.is_admin(array['super_admin']::public.app_role[]));
create policy "Members read own circle memberships"on public.circle_memberships for select to authenticated using((public.circles_enabled()and status='active'and public.is_circle_member(circle_id,auth.uid())and not public.is_blocked_pair(auth.uid(),user_id))or public.is_admin(array['super_admin']::public.app_role[]));
create policy "Members read own circle prompts"on public.circle_prompts for select to authenticated using((public.circles_enabled()and status='published'and opens_at<=now()and public.is_circle_member(circle_id,auth.uid()))or public.is_admin(array['super_admin']::public.app_role[]));
create policy "Members read circle prompt responses"on public.circle_prompt_responses for select to authenticated using((public.circles_enabled()and exists(select 1 from public.circle_prompts p join public.circle_memberships mine on mine.circle_id=p.circle_id and mine.user_id=auth.uid()and mine.status='active'join public.circle_memberships author on author.circle_id=p.circle_id and author.user_id=circle_prompt_responses.user_id and author.status='active'where p.id=prompt_id)and not public.is_blocked_pair(auth.uid(),user_id))or public.is_admin(array['super_admin']::public.app_role[]));

create or replace function public.circles_enabled()returns boolean language sql stable security definer set search_path=''as $$select coalesce((select enabled from public.feature_flags where key='circles'),false)$$;
create or replace function public.save_circle_cycle(p_cycle_id uuid,p_slug text,p_name text,p_description text,p_starts_at timestamptz,p_ends_at timestamptz,p_group_size integer,p_include_tests boolean,p_status text)returns uuid language plpgsql security definer set search_path=''as $$declare saved uuid:=p_cycle_id;begin if not public.is_admin(array['super_admin']::public.app_role[])then raise exception'Super admin required';end if;if p_status not in('draft','open','matched','published','completed')or p_group_size not between 3 and 8 or p_ends_at<=p_starts_at then raise exception'Invalid circle cycle configuration';end if;if p_cycle_id is null then insert into public.circle_cycles(slug,name,description,starts_at,ends_at,group_size,include_test_accounts,status,created_by)values(lower(trim(p_slug)),trim(p_name),trim(p_description),p_starts_at,p_ends_at,p_group_size,coalesce(p_include_tests,false),p_status,auth.uid())returning id into saved;else update public.circle_cycles set slug=lower(trim(p_slug)),name=trim(p_name),description=trim(p_description),starts_at=p_starts_at,ends_at=p_ends_at,group_size=p_group_size,include_test_accounts=coalesce(p_include_tests,false),status=p_status,updated_at=now()where id=p_cycle_id;if not found then raise exception'Circle cycle not found';end if;end if;insert into public.audit_events(actor_id,action,target_type,target_id,metadata)values(auth.uid(),'circle.cycle_saved','circle_cycle',saved,jsonb_build_object('status',p_status,'group_size',p_group_size,'include_tests',p_include_tests));return saved;end;$$;
create or replace function public.list_circle_cycles()returns table(cycle_id uuid,slug text,name text,description text,starts_at timestamptz,ends_at timestamptz,group_size integer,include_test_accounts boolean,status text,opt_in_status text,participant_count bigint,circle_count bigint)language plpgsql stable security definer set search_path=''as $$begin if auth.uid()is null then raise exception'Authentication required';end if;if not public.circles_enabled()and not public.is_admin(array['super_admin']::public.app_role[])then raise exception'Circles are not available yet';end if;return query select c.id,c.slug,c.name,c.description,c.starts_at,c.ends_at,c.group_size,c.include_test_accounts,c.status,o.status,(select count(*)from public.circle_opt_ins x where x.cycle_id=c.id and x.status in('opted_in','placed')),(select count(*)from public.circles x where x.cycle_id=c.id)from public.circle_cycles c left join public.circle_opt_ins o on o.cycle_id=c.id and o.user_id=auth.uid()where c.status in('open','matched','published','completed')or public.is_admin(array['super_admin']::public.app_role[])order by c.starts_at desc;end;$$;
create or replace function public.set_circle_opt_in(p_cycle_id uuid,p_join boolean,p_note text default null)returns void language plpgsql security definer set search_path=''as $$declare target public.circle_cycles%rowtype;begin if not public.circles_enabled()or not public.is_active_member(auth.uid())then raise exception'Active member access required';end if;select*into target from public.circle_cycles where id=p_cycle_id for share;if not found or target.status<>'open'then raise exception'This circle cycle is not accepting members';end if;if p_join then insert into public.circle_opt_ins(cycle_id,user_id,note,status)values(p_cycle_id,auth.uid(),nullif(trim(p_note),''),'opted_in')on conflict(cycle_id,user_id)do update set note=excluded.note,status='opted_in',updated_at=now();else update public.circle_opt_ins set status='withdrawn',updated_at=now()where cycle_id=p_cycle_id and user_id=auth.uid();end if;insert into public.audit_events(actor_id,action,target_type,target_id)values(auth.uid(),case when p_join then'circle.opted_in'else'circle.withdrew'end,'circle_cycle',p_cycle_id);end;$$;
create or replace function public.run_circle_matching(p_cycle_id uuid)returns integer language plpgsql security definer set search_path=''as $$declare target public.circle_cycles%rowtype;eligible_count integer;group_count integer;group_no integer;saved_circle uuid;begin if not public.is_admin(array['super_admin']::public.app_role[])then raise exception'Super admin required';end if;select*into target from public.circle_cycles where id=p_cycle_id for update;if not found or target.status not in('open','matched')then raise exception'Cycle must be open before matching';end if;if exists(select 1 from public.circles where cycle_id=p_cycle_id and status<>'draft')then raise exception'Published circles cannot be rematched';end if;delete from public.circles where cycle_id=p_cycle_id;create temporary table circle_eligible on commit drop as select p.id as user_id,row_number()over(order by coalesce(p.city,''),coalesce((select min(g.goal_key)from public.member_goals g where g.user_id=p.id),''),coalesce(p.industry,''),md5(p.id::text||p_cycle_id::text))as rn,p.city,p.industry,coalesce((select array_agg(g.goal_key order by g.goal_key)from public.member_goals g where g.user_id=p.id),array[]::text[])as goals from public.circle_opt_ins o join public.profiles p on p.id=o.user_id where o.cycle_id=p_cycle_id and o.status='opted_in'and p.access_status='active'and not p.visibility_paused and(target.include_test_accounts or not p.is_test_account);select count(*)into eligible_count from circle_eligible;if eligible_count<target.group_size then raise exception'At least % eligible members are required',target.group_size;end if;group_count:=ceil(eligible_count::numeric/target.group_size)::integer;for group_no in 1..group_count loop insert into public.circles(cycle_id,sequence,name)values(p_cycle_id,group_no,target.name||' · Circle '||lpad(group_no::text,2,'0'))returning id into saved_circle;insert into public.circle_memberships(circle_id,cycle_id,user_id,match_score,match_explanation)select saved_circle,p_cycle_id,e.user_id,least(100,50+coalesce((select profile_completion from public.profiles where id=e.user_id),0)/2),jsonb_build_object('method','deterministic_v1','city',e.city,'industry',e.industry,'goals',e.goals)from circle_eligible e where floor((e.rn-1)*group_count/eligible_count)+1=group_no;end loop;update public.circle_opt_ins set status='placed',updated_at=now()where cycle_id=p_cycle_id and user_id in(select user_id from circle_eligible);update public.circle_cycles set status='matched',updated_at=now()where id=p_cycle_id;insert into public.audit_events(actor_id,action,target_type,target_id,metadata)values(auth.uid(),'circle.matching_completed','circle_cycle',p_cycle_id,jsonb_build_object('eligible',eligible_count,'circles',group_count,'method','deterministic_v1'));return group_count;end;$$;
create or replace function public.publish_circle_cycle(p_cycle_id uuid)returns void language plpgsql security definer set search_path=''as $$declare member record;begin if not public.is_admin(array['super_admin']::public.app_role[])then raise exception'Super admin required';end if;update public.circle_cycles set status='published',updated_at=now()where id=p_cycle_id and status='matched';if not found then raise exception'Matched cycle required';end if;update public.circles set status='published',updated_at=now()where cycle_id=p_cycle_id;for member in select m.user_id,c.name from public.circle_memberships m join public.circles c on c.id=m.circle_id where m.cycle_id=p_cycle_id loop perform public.enqueue_notification(member.user_id,'community','Your Circle is ready',member.name||' is now open. Meet your cohort and respond to the first prompt.','/circles','circle-published:'||p_cycle_id||':'||member.user_id);end loop;insert into public.audit_events(actor_id,action,target_type,target_id)values(auth.uid(),'circle.cycle_published','circle_cycle',p_cycle_id);end;$$;
create or replace function public.list_my_circles()returns table(circle_id uuid,cycle_id uuid,cycle_name text,circle_name text,starts_at timestamptz,ends_at timestamptz,member_count bigint,prompt_count bigint)language plpgsql stable security definer set search_path=''as $$begin if not public.circles_enabled()or not public.is_active_member(auth.uid())then raise exception'Active member access required';end if;return query select c.id,c.cycle_id,cy.name,c.name,cy.starts_at,cy.ends_at,(select count(*)from public.circle_memberships x where x.circle_id=c.id and x.status='active'),(select count(*)from public.circle_prompts x where x.circle_id=c.id and x.status='published'and x.opens_at<=now())from public.circles c join public.circle_cycles cy on cy.id=c.cycle_id join public.circle_memberships m on m.circle_id=c.id and m.user_id=auth.uid()and m.status='active'where c.status='published'and cy.status in('published','completed')order by cy.starts_at desc;end;$$;
create or replace function public.list_circle_members(p_circle_id uuid)returns table(user_id uuid,display_name text,avatar_url text,job_title text,company text,city text,country text,goals text[],role text)language plpgsql stable security definer set search_path=''as $$begin if not exists(select 1 from public.circle_memberships where circle_id=p_circle_id and user_id=auth.uid()and status='active')then raise exception'Circle membership required';end if;return query select p.id,p.display_name,p.avatar_url,p.job_title,p.company,p.city,p.country,coalesce((select array_agg(g.goal_key order by g.goal_key)from public.member_goals g where g.user_id=p.id),array[]::text[]),m.role from public.circle_memberships m join public.profiles p on p.id=m.user_id where m.circle_id=p_circle_id and m.status='active'and p.access_status='active'and not public.is_blocked_pair(auth.uid(),p.id)order by m.role desc,p.display_name;end;$$;
create or replace function public.list_circle_prompts(p_circle_id uuid)returns table(prompt_id uuid,title text,body text,opens_at timestamptz,due_at timestamptz,own_response text,response_count bigint)language plpgsql stable security definer set search_path=''as $$begin if not exists(select 1 from public.circle_memberships where circle_id=p_circle_id and user_id=auth.uid()and status='active')then raise exception'Circle membership required';end if;return query select p.id,p.title,p.body,p.opens_at,p.due_at,r.body,(select count(*)from public.circle_prompt_responses x where x.prompt_id=p.id)from public.circle_prompts p left join public.circle_prompt_responses r on r.prompt_id=p.id and r.user_id=auth.uid()where p.circle_id=p_circle_id and p.status='published'and p.opens_at<=now()order by p.opens_at desc;end;$$;
create or replace function public.save_circle_response(p_prompt_id uuid,p_body text)returns uuid language plpgsql security definer set search_path=''as $$declare saved uuid;target_circle uuid;begin select circle_id into target_circle from public.circle_prompts where id=p_prompt_id and status='published'and opens_at<=now()and(due_at is null or due_at>now());if target_circle is null or not exists(select 1 from public.circle_memberships where circle_id=target_circle and user_id=auth.uid()and status='active')then raise exception'Open Circle prompt required';end if;insert into public.circle_prompt_responses(prompt_id,user_id,body)values(p_prompt_id,auth.uid(),trim(p_body))on conflict(prompt_id,user_id)do update set body=excluded.body,updated_at=now()returning id into saved;return saved;end;$$;
create or replace function public.publish_circle_prompt(p_cycle_id uuid,p_title text,p_body text,p_opens_at timestamptz,p_due_at timestamptz)returns integer language plpgsql security definer set search_path=''as $$declare created_count integer;begin if not public.is_admin(array['super_admin']::public.app_role[])then raise exception'Super admin required';end if;if p_due_at is not null and p_due_at<=p_opens_at then raise exception'Due date must follow opening';end if;with inserted as(insert into public.circle_prompts(circle_id,title,body,opens_at,due_at,status,created_by)select id,trim(p_title),trim(p_body),p_opens_at,p_due_at,'published',auth.uid()from public.circles where cycle_id=p_cycle_id and status='published'returning id)select count(*)into created_count from inserted;if created_count=0 then raise exception'Published circles required';end if;insert into public.notifications(user_id,kind,title,body,href,dedupe_key)select m.user_id,'community','A new Circle prompt',trim(p_title),'/circles','circle-prompt:'||p_cycle_id||':'||m.user_id||':'||md5(trim(p_title)||p_opens_at::text)from public.circle_memberships m where m.cycle_id=p_cycle_id and m.status='active'on conflict(user_id,dedupe_key)do nothing;insert into public.audit_events(actor_id,action,target_type,target_id,metadata)values(auth.uid(),'circle.prompt_published','circle_cycle',p_cycle_id,jsonb_build_object('circle_count',created_count,'title',trim(p_title)));return created_count;end;$$;
create or replace function public.list_circle_participants_admin(p_cycle_id uuid)returns table(circle_id uuid,circle_name text,user_id uuid,email text,display_name text,is_test_account boolean,city text,industry text,goals text[],match_score integer,status text)language plpgsql stable security definer set search_path=''as $$begin if not public.is_admin(array['super_admin']::public.app_role[])then raise exception'Super admin required';end if;return query select c.id,c.name,m.user_id,u.email::text,p.display_name,p.is_test_account,p.city,p.industry,coalesce((select array_agg(g.goal_key order by g.goal_key)from public.member_goals g where g.user_id=p.id),array[]::text[]),m.match_score,m.status from public.circle_memberships m join public.circles c on c.id=m.circle_id join auth.users u on u.id=m.user_id join public.profiles p on p.id=m.user_id where m.cycle_id=p_cycle_id order by c.sequence,p.display_name;end;$$;

revoke all on function public.circles_enabled()from public;grant execute on function public.circles_enabled()to authenticated;revoke all on function public.save_circle_cycle(uuid,text,text,text,timestamptz,timestamptz,integer,boolean,text)from public;grant execute on function public.save_circle_cycle(uuid,text,text,text,timestamptz,timestamptz,integer,boolean,text)to authenticated;revoke all on function public.list_circle_cycles()from public;grant execute on function public.list_circle_cycles()to authenticated;revoke all on function public.set_circle_opt_in(uuid,boolean,text)from public;grant execute on function public.set_circle_opt_in(uuid,boolean,text)to authenticated;revoke all on function public.run_circle_matching(uuid)from public;grant execute on function public.run_circle_matching(uuid)to authenticated;revoke all on function public.publish_circle_cycle(uuid)from public;grant execute on function public.publish_circle_cycle(uuid)to authenticated;revoke all on function public.list_my_circles()from public;grant execute on function public.list_my_circles()to authenticated;revoke all on function public.list_circle_members(uuid)from public;grant execute on function public.list_circle_members(uuid)to authenticated;revoke all on function public.list_circle_prompts(uuid)from public;grant execute on function public.list_circle_prompts(uuid)to authenticated;revoke all on function public.save_circle_response(uuid,text)from public;grant execute on function public.save_circle_response(uuid,text)to authenticated;revoke all on function public.publish_circle_prompt(uuid,text,text,timestamptz,timestamptz)from public;grant execute on function public.publish_circle_prompt(uuid,text,text,timestamptz,timestamptz)to authenticated;revoke all on function public.list_circle_participants_admin(uuid)from public;grant execute on function public.list_circle_participants_admin(uuid)to authenticated;
revoke all on function public.is_circle_member(uuid,uuid)from public;grant execute on function public.is_circle_member(uuid,uuid)to authenticated;

create or replace function public.list_circle_responses(p_prompt_id uuid)returns table(response_id uuid,user_id uuid,display_name text,avatar_url text,body text,updated_at timestamptz)language plpgsql stable security definer set search_path=''as $$declare target_circle uuid;begin select circle_id into target_circle from public.circle_prompts where id=p_prompt_id and status='published'and opens_at<=now();if target_circle is null or not public.is_circle_member(target_circle,auth.uid())then raise exception'Circle membership required';end if;return query select r.id,r.user_id,p.display_name,p.avatar_url,r.body,r.updated_at from public.circle_prompt_responses r join public.profiles p on p.id=r.user_id join public.circle_memberships m on m.circle_id=target_circle and m.user_id=r.user_id and m.status='active'where r.prompt_id=p_prompt_id and not public.is_blocked_pair(auth.uid(),r.user_id)order by r.updated_at;end;$$;
revoke all on function public.list_circle_responses(uuid)from public;grant execute on function public.list_circle_responses(uuid)to authenticated;

-- Hardened final matcher: balanced deterministic groups and a blocking safety gate.
create or replace function public.run_circle_matching(p_cycle_id uuid)returns integer language plpgsql security definer set search_path=''as $$
declare target public.circle_cycles%rowtype;eligible_count integer;group_count integer;group_no integer;saved_circle uuid;
begin
 if not public.is_admin(array['super_admin']::public.app_role[])then raise exception'Super admin required';end if;
 select*into target from public.circle_cycles where id=p_cycle_id for update;
 if not found or target.status not in('open','matched')then raise exception'Cycle must be open before matching';end if;
 if exists(select 1 from public.circles where cycle_id=p_cycle_id and status<>'draft')then raise exception'Published circles cannot be rematched';end if;
 delete from public.circles where cycle_id=p_cycle_id;
 create temporary table circle_eligible on commit drop as
 select p.id as user_id,row_number()over(order by coalesce(p.city,''),coalesce((select min(g.goal_key)from public.member_goals g where g.user_id=p.id),''),coalesce(p.industry,''),md5(p.id::text||p_cycle_id::text))as rn,p.city,p.industry,coalesce((select array_agg(g.goal_key order by g.goal_key)from public.member_goals g where g.user_id=p.id),array[]::text[])as goals
 from public.circle_opt_ins o join public.profiles p on p.id=o.user_id
 where o.cycle_id=p_cycle_id and o.status in('opted_in','placed')and p.access_status='active'and not p.visibility_paused and(target.include_test_accounts or not p.is_test_account);
 select count(*)into eligible_count from circle_eligible;
 if eligible_count<target.group_size then raise exception'At least % eligible members are required',target.group_size;end if;
 group_count:=ceil(eligible_count::numeric/target.group_size)::integer;
 for group_no in 1..group_count loop
  insert into public.circles(cycle_id,sequence,name)values(p_cycle_id,group_no,target.name||' · Circle '||lpad(group_no::text,2,'0'))returning id into saved_circle;
  insert into public.circle_memberships(circle_id,cycle_id,user_id,match_score,match_explanation)
  select saved_circle,p_cycle_id,e.user_id,least(100,50+coalesce((select profile_completion from public.profiles where id=e.user_id),0)/2),jsonb_build_object('method','deterministic_v1','city',e.city,'industry',e.industry,'goals',e.goals)
  from circle_eligible e where((e.rn-1)*group_count/eligible_count)+1=group_no;
 end loop;
 if exists(select 1 from public.circle_memberships a join public.circle_memberships b on b.circle_id=a.circle_id and b.user_id>a.user_id where a.cycle_id=p_cycle_id and public.is_blocked_pair(a.user_id,b.user_id))then raise exception'Matching produced a blocked pair; change the group size or participant pool';end if;
 update public.circle_opt_ins set status='placed',updated_at=now()where cycle_id=p_cycle_id and user_id in(select user_id from circle_eligible);
 update public.circle_cycles set status='matched',updated_at=now()where id=p_cycle_id;
 insert into public.audit_events(actor_id,action,target_type,target_id,metadata)values(auth.uid(),'circle.matching_completed','circle_cycle',p_cycle_id,jsonb_build_object('eligible',eligible_count,'circles',group_count,'method','deterministic_v1'));
 return group_count;
end;$$;

-- Cycle editing cannot impersonate the matching or publication state transitions.
create or replace function public.save_circle_cycle(p_cycle_id uuid,p_slug text,p_name text,p_description text,p_starts_at timestamptz,p_ends_at timestamptz,p_group_size integer,p_include_tests boolean,p_status text)returns uuid language plpgsql security definer set search_path=''as $$
declare saved uuid:=p_cycle_id;current_status text;
begin
 if not public.is_admin(array['super_admin']::public.app_role[])then raise exception'Super admin required';end if;
 if p_status not in('draft','open','completed')or p_group_size not between 3 and 8 or p_ends_at<=p_starts_at then raise exception'Invalid circle cycle configuration';end if;
 if p_cycle_id is null then
  insert into public.circle_cycles(slug,name,description,starts_at,ends_at,group_size,include_test_accounts,status,created_by)values(lower(trim(p_slug)),trim(p_name),trim(p_description),p_starts_at,p_ends_at,p_group_size,coalesce(p_include_tests,false),p_status,auth.uid())returning id into saved;
 else
  select status into current_status from public.circle_cycles where id=p_cycle_id for update;if current_status is null then raise exception'Circle cycle not found';end if;
  if current_status in('matched','published')and p_status<>'completed'then raise exception'Matched and published cycles are changed only through release controls';end if;
  update public.circle_cycles set slug=lower(trim(p_slug)),name=trim(p_name),description=trim(p_description),starts_at=p_starts_at,ends_at=p_ends_at,group_size=p_group_size,include_test_accounts=coalesce(p_include_tests,false),status=p_status,updated_at=now()where id=p_cycle_id;
 end if;
 insert into public.audit_events(actor_id,action,target_type,target_id,metadata)values(auth.uid(),'circle.cycle_saved','circle_cycle',saved,jsonb_build_object('status',p_status,'group_size',p_group_size,'include_tests',p_include_tests));return saved;
end;$$;

-- Final read/write definitions enforce the feature gate even through SECURITY DEFINER RPCs.
create or replace function public.list_circle_members(p_circle_id uuid)returns table(user_id uuid,display_name text,avatar_url text,job_title text,company text,city text,country text,goals text[],role text)language plpgsql stable security definer set search_path=''as $$begin if not public.circles_enabled()or not public.is_circle_member(p_circle_id,auth.uid())then raise exception'Circle membership required';end if;return query select p.id,p.display_name,p.avatar_url,p.job_title,p.company,p.city,p.country,coalesce((select array_agg(g.goal_key order by g.goal_key)from public.member_goals g where g.user_id=p.id),array[]::text[]),m.role from public.circle_memberships m join public.profiles p on p.id=m.user_id where m.circle_id=p_circle_id and m.status='active'and p.access_status='active'and not public.is_blocked_pair(auth.uid(),p.id)order by m.role desc,p.display_name;end;$$;
create or replace function public.list_circle_prompts(p_circle_id uuid)returns table(prompt_id uuid,title text,body text,opens_at timestamptz,due_at timestamptz,own_response text,response_count bigint)language plpgsql stable security definer set search_path=''as $$begin if not public.circles_enabled()or not public.is_circle_member(p_circle_id,auth.uid())then raise exception'Circle membership required';end if;return query select p.id,p.title,p.body,p.opens_at,p.due_at,r.body,(select count(*)from public.circle_prompt_responses x where x.prompt_id=p.id and not public.is_blocked_pair(auth.uid(),x.user_id))from public.circle_prompts p left join public.circle_prompt_responses r on r.prompt_id=p.id and r.user_id=auth.uid()where p.circle_id=p_circle_id and p.status='published'and p.opens_at<=now()order by p.opens_at desc;end;$$;
create or replace function public.save_circle_response(p_prompt_id uuid,p_body text)returns uuid language plpgsql security definer set search_path=''as $$declare saved uuid;target_circle uuid;begin if not public.circles_enabled()then raise exception'Circles are not available yet';end if;select circle_id into target_circle from public.circle_prompts where id=p_prompt_id and status='published'and opens_at<=now()and(due_at is null or due_at>now());if target_circle is null or not public.is_circle_member(target_circle,auth.uid())then raise exception'Open Circle prompt required';end if;insert into public.circle_prompt_responses(prompt_id,user_id,body)values(p_prompt_id,auth.uid(),trim(p_body))on conflict(prompt_id,user_id)do update set body=excluded.body,updated_at=now()returning id into saved;return saved;end;$$;
create or replace function public.list_circle_responses(p_prompt_id uuid)returns table(response_id uuid,user_id uuid,display_name text,avatar_url text,body text,updated_at timestamptz)language plpgsql stable security definer set search_path=''as $$declare target_circle uuid;begin if not public.circles_enabled()then raise exception'Circles are not available yet';end if;select circle_id into target_circle from public.circle_prompts where id=p_prompt_id and status='published'and opens_at<=now();if target_circle is null or not public.is_circle_member(target_circle,auth.uid())then raise exception'Circle membership required';end if;return query select r.id,r.user_id,p.display_name,p.avatar_url,r.body,r.updated_at from public.circle_prompt_responses r join public.profiles p on p.id=r.user_id join public.circle_memberships m on m.circle_id=target_circle and m.user_id=r.user_id and m.status='active'where r.prompt_id=p_prompt_id and not public.is_blocked_pair(auth.uid(),r.user_id)order by r.updated_at;end;$$;

comment on table public.circle_cycles is'Deliberately released deterministic cohort cycles. Matching configuration and test inclusion are auditable.';comment on column public.circle_memberships.match_explanation is'Transparent deterministic matching factors; never an opaque AI score.';
commit;
